name: circular_ordering-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.15
  - ipython=8.6.0  
  - jupyter=1.0.0
  - matplotlib=3.6.2
  - numpy=1.24.1
  - scipy=1.10.1
  - seaborn=0.13.2
  - statsmodels=0.13.5
  - pandas=1.5.2
  - biothings_client=0.2.6
  - pyarrow=10.0.1
  - scikit-learn=1.2.2

